Modules =
    cliargumentsmodule: require "./cliargumentsmodule"
    cloudservicemodule: require "./cloudservicemodule"
    configmodule: require "./configmodule"
    constructionmodule: require "./constructionmodule"
    createprocessmodule: require "./createprocessmodule"
    debugmodule: require "./debugmodule"
    encryptionmodule: require "./encryptionmodule"
    githubservicemodule: require "./githubservicemodule"
    gitlabservicemodule: require "./gitlabservicemodule"
    gitmodule: require "./gitmodule"
    globalscopemodule: require "./globalscopemodule"
    pathhandlermodule: require "./pathhandlermodule"
    recipemodule: require "./recipemodule"
    remotehandlermodule: require "./remotehandlermodule"
    startupmodule: require "./startupmodule"
    thingymodule: require "./thingymodule"
    transformationmodule: require "./transformationmodule"
    urlhandlermodule: require "./urlhandlermodule"
    useractionmodule: require "./useractionmodule"
    userconfigmodule: require "./userconfigmodule"
    userinquirermodule: require "./userinquirermodule"

module.exports = Modules